[package]
name = "nft_ingester"
version = "0.7.2"
edition = "2021"
publish = false

[dependencies]
serde_derive = "1.0.190"
hex = "0.4.3"
log = "0.4.17"
env_logger = "0.10.0"
redis = { version = "0.22.3", features = ["aio", "tokio-comp", "streams", "tokio-native-tls-comp"] }
futures = { version = "0.3.25" }
futures-util = "0.3.27"
base64 = "0.21.0"
thiserror = "1.0.31"
serde_json = "1.0.81"
tokio = { version = "1.26.0", features = ["full", "tracing"] }
sqlx = { version = "0.6.2", features = ["macros", "runtime-tokio-rustls", "postgres", "uuid", "offline", "json"] }
sea-orm = { version = "0.10.6", features = ["macros", "runtime-tokio-rustls", "sqlx-postgres", "with-chrono", "mock"] }
sea-query = { version = "0.28.1", features = ["postgres-array"] }
chrono = "0.4.19"
tokio-postgres = "0.7.7"
serde = "1.0.136"
bs58 = "0.4.0"
reqwest = "0.11.11"
plerkle_messenger = { version = "1.5.2", features = ['redis'] }
plerkle_serialization = { version = "1.5.2" }
flatbuffers = "23.1.21"
lazy_static = "1.4.0"
regex = "1.5.5"
mpl-bubblegum = { git = "https://github.com/metaplex-foundation/mpl-bubblegum.git", rev = "3cb3976d", features = ["no-entrypoint"] }
spl-account-compression = "0.1.8"
spl-concurrent-merkle-tree = "0.1.3"
uuid = "1.0.0"
async-trait = "0.1.53"
num-traits = "0.2.15"
blockbuster = { git = "https://github.com/metaplex-foundation/blockbuster.git", rev = "552aba6a" }
figment = { version = "0.10.6", features = ["env", "toml", "yaml"] }
cadence = "0.29.0"
cadence-macros = "0.29.0"
solana-sdk = "~1.14"
solana-client = "~1.14"
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
solana-transaction-status = "~1.14"
solana-account-decoder = "~1.14"
solana-geyser-plugin-interface = { version = "~1.14" }
solana-sdk-macro = "~1.14"
solana-storage-bigtable = "~1.14"
solana-bigtable-connection = "1.10.31"
rand = "0.8.5"
rust-crypto = "0.2.36"
url = "2.3.1"
anchor-lang = "=0.26.0"
borsh = "0.9.1"
stretto = { version = "0.7", features = ["async"] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.10", features = ["codec", "compat"] }
tracing-subscriber = { version = "0.3.16", features = [
    "json",
    "env-filter",
    "ansi",
] }
clap = { version = "4.2.2", features = ["derive", "cargo"] }
bincode = "1.3.3"
metrics-utils = { path = "../metrics_utils" }
rocks-db = { path = "../rocks-db" }
postgre-client = { path = "../postgre-client" }
digital_asset_types = { path = "../digital_asset_types", features = ["json_types", "sql_types"] }
tower-http = { version = "0.3.5", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
hyper = "0.14.27"
open-rpc-derive = { version = "0.0.4" }
open-rpc-schema = { version = "0.0.4" }
schemars = "0.8.6"
schemars_derive = "0.8.6"
jsonrpc-core = "18.0.0"
jsonrpc-http-server = "18.0.0"
libc = "0.2.144"
crossbeam-channel = "0.5.8"
jsonrpc-derive = "18.0.0"
jsonrpc-core-client = "18.0.0"
semver = "1.0.19"
mockall = "0.11.4"
entities = { path = "../entities" }

[dev-dependencies]
tokio = { version = "1.35.0", features = ["macros", "test-util"] }

[dependencies.num-integer]
version = "0.1.44"
default-features = false

[dependencies.utils]
version = "0.1.8"
git = "https://github.com/extrnode/solana-geyser-zmq"

[[bin]]
name = "ingester"

[[bin]]
name = "migrator"
