[package]
name = "rocks-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { version = "0.21.0", features = ["multi-threaded-cf"] }
solana-sdk = "~1.16"
bincode = "1.3.3"
serde = "1.0.193"
thiserror = "1.0.50"
num_cpus = "1.16.0"
log = "0.4.17"
figment = { version = "0.10.6", features = ["env", "toml", "yaml"] }
lz4 = "1.24.0"
tar = "0.4.40"
reqwest = { version = "0.11.22", features = ["stream"] }
futures-util = "0.3.29"
metrics-utils = { path = "../metrics_utils" }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
spl-account-compression = "0.2.0"
chrono = "0.4.31"
serde_json = "1.0.81"
mockall = "0.12.0"
async-trait = "0.1.74"
tokio-stream = "0.1.14"
entities = { path = "../entities" }
interface = { path = "../interface" }

[dev-dependencies]
tempfile = "3.8.1"
rand = "0.8.5"
setup = { path = "../tests/setup" }

[features]
integration_tests = []