[package]
name = "rocks-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { version = "0.21.0", features = ["multi-threaded-cf"] }
solana-sdk = { workspace = true }
bincode = "1.3.3"
serde = "1.0.193"
thiserror = "1.0.50"
num_cpus = "1.16.0"
log = "0.4.17"
figment = { version = "0.10.6", features = ["env", "toml", "yaml"] }
lz4 = "1.24.0"
tar = "0.4.40"
reqwest = { version = "0.11.22", features = ["stream"] }
futures-util = "0.3.29"
metrics-utils = { path = "../metrics_utils" }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
spl-account-compression = { git = "https://github.com/StanChe/solana-program-library.git", branch = "feature/init_with_root", features = ["no-entrypoint"] }
chrono = "0.4.31"
serde_json = "1.0.81"
mockall = "0.12.0"
async-trait = "0.1.74"
tokio-stream = "0.1.14"
entities = { path = "../entities" }
interface = { path = "../interface" }
solana-transaction-status = "~1.18.11"
tracing = "0.1.40"
serde_cbor = "0.11.2"
mpl-token-metadata = { version = "3.2.3"}
rustyline = "13.0.0"
csv = "1.3.0"
hex = "0.4.3"
Inflector = "0.11.4"
base64 = "0.21.5"
usecase = { path = "../usecase" }
tempfile = "3.8.1"
bubblegum-batch-sdk = { git = "https://github.com/metaplex-foundation/bubblegum-batch-sdk.git", rev = "0d529f5" }

[dev-dependencies]
rand = "0.8.5"
setup = { path = "../tests/setup" }
criterion = "0.5.1"
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }

[features]
integration_tests = []

[[bench]]
name = "misc_benchmark"
harness = false

[[bench]]
name = "dump_benchmark"
harness = false

[[bin]]
name = "column_remover"

[[bin]]
name = "column_copier"
