[workspace]
resolver = "2"
members = [
  "nft_ingester",
  "metrics_utils",
  "rocks-db",
  "postgre-client",
  "entities",
  "grpc",
  "interface",
  "usecase",
  "tests/setup",
  "backfill_rpc",
  "integrity_verification"
]
exclude = [
  "blockbuster/blockbuster",
  "blockbuster/mpl-bubblegum",
  "rollup-sdk",
]

[workspace.dependencies]
thiserror = { version = "1"}
solana-sdk = { version = "~1.18.11" }
solana-program = { version = "~1.18.11" }

[profile.release]
lto = true
codegen-units = 1
