[workspace]
members = [
  "digital_asset_types",
  "nft_ingester",
  "metrics_utils",
  "rocks-db",
  "postgre-client",
  "entities",
]
exclude = [
  "migration",
]

[profile.release]
lto = true
codegen-units = 1
