version: "3.9"
services:
  ingester-first-consumer:
    container_name: ingester-first-consumer
    restart: always
    entrypoint: "./ingester"
    env_file:
      - .env
    environment:
      INGESTER_CONSUMER_NUMBER: 0
    network_mode: host
    volumes:
      - ${INGESTER_ROCKS_DB_PATH}:${INGESTER_ROCKS_DB_PATH_CONTAINER}:rw
      - ${INGESTER_ROCKS_BACKUP_DIR}:${INGESTER_ROCKS_BACKUP_DIR}:rw
      - ${INGESTER_ROCKS_BACKUP_ARCHIVES_DIR}:${INGESTER_ROCKS_BACKUP_ARCHIVES_DIR}:rw
      - ${INGESTER_PROFILING_FILE_PATH}:${INGESTER_PROFILING_FILE_PATH_CONTAINER}:rw
      - ./creds.json:/usr/src/app/creds.json
    depends_on:
      - db
    build:
      context: .
      dockerfile: ingester.Dockerfile
    logging:
      options:
        max-size: "2048m"

raw-backriller:
    container_name: raw-backriller
    restart: always
    entrypoint: "./raw_backfiller"
    env_file:
      - .env
    network_mode: host
    volumes:
      - ${INGESTER_ROCKS_DB_PATH}:${INGESTER_ROCKS_DB_PATH_CONTAINER}:rw
      - ${INGESTER_PROFILING_FILE_PATH}:${INGESTER_PROFILING_FILE_PATH_CONTAINER}:rw
      - ./creds.json:/usr/src/app/creds.json
    build:
      context: .
      dockerfile: ingester.Dockerfile
    logging:
      options:
        max-size: "2048m"

  db:
    container_name: db
    image: 'postgres:14'
    command: [ "postgres", "-c", "log_statement=none", "-c", "log_destination=stderr" ,"-c","max_connections=2000", "-c", "max_parallel_workers=32", "-c", "max_parallel_workers_per_gather=24", "-c", "max_parallel_maintenance_workers=8", "-c", "shared_buffers=30GB", "-c", "effective_cache_size=55GB", "-c", "work_mem=1GB" ]
    shm_size: 1g
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: solana # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: solana # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: solana
    volumes:
      - ${POSTGRE_DB_PATH:-./db-data}:/var/lib/postgresql/data/:rw
    logging:
      options:
        max-size: "100m"
