version: "3.9"
services:
  ingester-first-consumer:
    container_name: ingester-first-consumer
    restart: always
    entrypoint: sh -c "if [ -z '$$MALLOC_CONF' ]; then exec ./ingester; else exec ./profiling_ingester; fi"
    env_file:
      - .env
    environment:
      INGESTER_CONSUMER_NUMBER: 0
    network_mode: host
    volumes:
      - ${INGESTER_ROCKS_DB_PATH}:${INGESTER_ROCKS_DB_PATH_CONTAINER}:rw
      - ${INGESTER_SYNCHRONIZER_DUMP_PATH:-/tmp/rocks_dump}:${INGESTER_SYNCHRONIZER_DUMP_PATH:-/tmp/rocks_dump}:rw
      - ${INGESTER_ROCKS_BACKUP_DIR}:${INGESTER_ROCKS_BACKUP_DIR}:rw
      - ${INGESTER_ROCKS_BACKUP_ARCHIVES_DIR}:${INGESTER_ROCKS_BACKUP_ARCHIVES_DIR}:rw
      - ${INGESTER_PROFILING_FILE_PATH}:${INGESTER_PROFILING_FILE_PATH_CONTAINER}:rw
      - ${INGESTER_FILE_STORAGE_PATH}:${INGESTER_FILE_STORAGE_PATH_CONTAINER}:rw
      - ./creds.json:/usr/src/app/creds.json
      - ./migrations:/usr/src/app/migrations
      - ./heaps:/usr/src/app/heaps:rw
    depends_on:
      - db
    build:
      context: .
      dockerfile: ingester.Dockerfile
    stop_grace_period: 10m
    logging:
      options:
        max-size: "2048m"

  das-api:
    container_name: das-api
    restart: always
    entrypoint: sh -c "if [ -z '$$MALLOC_CONF' ]; then exec ./api; else exec ./profiling_api; fi"
    env_file:
      - .env
    network_mode: host
    volumes:
      - ${API_ROCKS_DB_PATH_CONTAINER}:${API_ROCKS_DB_PATH_CONTAINER}:ro
      - ${API_ROCKS_DB_SECONDARY_PATH_CONTAINER}:${API_ROCKS_DB_SECONDARY_PATH_CONTAINER}:rw
      - ${API_ARCHIVES_DIR}:${API_ARCHIVES_DIR}:ro
      - ${API_FILE_STORAGE_PATH}:${API_FILE_STORAGE_PATH_CONTAINER}:rw
      - ./heaps:/usr/src/app/heaps:rw
    depends_on:
      - db
    build:
      context: .
      dockerfile: ingester.Dockerfile
    stop_grace_period: 10m
    logging:
      options:
        max-size: "2048m"

  synchronizer:
    container_name: synchronizer
    restart: always
    entrypoint: sh -c "if [ -z '$$MALLOC_CONF' ]; then exec ./synchronizer; else exec ./profiling_synchronizer; fi"
    env_file:
      - .env
    network_mode: host
    volumes:
      - ${INGESTER_ROCKS_DB_PATH}:${INGESTER_ROCKS_DB_PATH_CONTAINER}:rw
      - ${SYNCHRONIZER_DUMP_PATH:-/tmp/rocks_dump}:${SYNCHRONIZER_DUMP_PATH:-/tmp/rocks_dump}:rw
      - ${SYNCHRONIZER_ROCKS_DB_SECONDARY_PATH_CONTAINER}:${SYNCHRONIZER_ROCKS_DB_SECONDARY_PATH_CONTAINER}:rw
      - ./heaps:/usr/src/app/heaps:rw
    depends_on:
      - db
    build:
      context: .
      dockerfile: ingester.Dockerfile
    stop_grace_period: 10m
    logging:
      options:
        max-size: "2048m"

  integrity-verification:
    container_name: integrity-verification
    restart: always
    entrypoint: "./integrity-verification"
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./creds.json:/usr/src/app/creds.json
      - ${INTEGRITY_VERIFICATION_TEST_FILE_PATH}:${INTEGRITY_VERIFICATION_TEST_FILE_PATH_CONTAINER}:rw
      - ${INTEGRITY_VERIFICATION_SLOTS_COLLECT_PATH}:${INTEGRITY_VERIFICATION_SLOTS_COLLECT_PATH_CONTAINER}:rw
    depends_on:
      - db
    build:
      context: .
      dockerfile: integrity_verification.Dockerfile
    logging:
      options:
        max-size: "2048m"

  raw-backfiller:
    container_name: raw-backfiller
    restart: always
    entrypoint: sh -c "if [ -z '$$MALLOC_CONF' ]; then exec ./raw_backfiller; else exec ./profiling_raw_backfiller; fi"
    env_file:
      - .env
    network_mode: host
    volumes:
      - ${INGESTER_ROCKS_DB_PATH}:${INGESTER_ROCKS_DB_PATH_CONTAINER}:rw
      - ${INGESTER_PROFILING_FILE_PATH}:${INGESTER_PROFILING_FILE_PATH_CONTAINER}:rw
      - ./creds.json:/usr/src/app/creds.json
      - ./heaps:/usr/src/app/heaps:rw
    stop_grace_period: 10m
    build:
      context: .
      dockerfile: ingester.Dockerfile
    logging:
      options:
        max-size: "2048m"

  db:
    container_name: db
    image: 'postgres:14'
    command: [ "postgres", "-c", "log_statement=none", "-c", "log_destination=stderr" ,"-c","max_connections=2000", "-c", "max_parallel_workers=32", "-c", "max_parallel_workers_per_gather=24", "-c", "max_parallel_maintenance_workers=8", "-c", "shared_buffers=30GB", "-c", "effective_cache_size=55GB", "-c", "work_mem=1GB", "-c", "max_wal_size=20GB" ]
    shm_size: 1g
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: solana # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: solana # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: solana
    volumes:
      - ${POSTGRE_DB_PATH:-./db-data}:/var/lib/postgresql/data/:rw
      - ${INGESTER_SYNCHRONIZER_DUMP_PATH:-/tmp/rocks_dump}:${INGESTER_SYNCHRONIZER_DUMP_PATH:-/tmp/rocks_dump}:ro
    logging:
      options:
        max-size: "100m"
