[package]
name = "entities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.193"
solana-sdk = "~1.17"
num-derive = "0.4.1"
num-traits = "0.2.17"
schemars = "0.8.6"
serde_derive = "1.0.195"
serde_with = "3.7.0"
sqlx = { version = "0.6.2", features = ["macros", "runtime-tokio-rustls", "postgres", "uuid", "offline", "json", "chrono"] }
solana-program = "~1.17"
blockbuster = "2.2.1"
sha2 = "0.10.0"
mpl-bubblegum = {version = "1.2.0", features = ["serde"] }
serde_json = "1.0.81"
spl-account-compression = "0.3.0"

[dev-dependencies]
hex = "0.4.3"
