[package]
name = "entities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.193"
solana-sdk = "~1.16"
num-derive = "0.4.1"
num-traits = "0.2.17"
schemars = "0.8.6"