[package]
name = "usecase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.75"
entities = { path = "../entities" }
interface = { path = "../interface" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["full", "tracing"] }
mockall = "0.12.0"
futures = "0.3.30"
