[package]
name = "usecase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.75"
entities = { path = "../entities" }
interface = { path = "../interface" }
tracing = "0.1.40"
solana-sdk = { version = "~1.16" }
metrics-utils = { path = "../metrics_utils" }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
solana-storage-bigtable = "~1.16"
solana-bigtable-connection = "1.10.31"
solana-transaction-status = "~1.16"
mpl-bubblegum = "1.0.1-beta.4"

[dev-dependencies]
mockall = "0.12.0"
futures = "0.3.30"
