[package]
name = "usecase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.75"
entities = { path = "../entities" }
interface = { path = "../interface" }
tracing = "0.1.40"
solana-sdk = { workspace = true }
metrics-utils = { path = "../metrics_utils" }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
solana-storage-bigtable = "~1.18.11"
solana-bigtable-connection = "1.10.31"
solana-transaction-status = "~1.18.11"
mpl-bubblegum = {path = "../blockbuster/mpl-bubblegum/clients/rust", features = ["serde"] }
mockall = "0.12.0"
spl-account-compression = { git = "https://github.com/StanChe/solana-program-library.git", branch = "feature/init_with_root", features = ["no-entrypoint"] }
solana-client = "~1.18.11"
solana-program = { workspace = true }
spl-concurrent-merkle-tree = { path = "../blockbuster/mpl-bubblegum/solana-program-library/libraries/concurrent-merkle-tree" }
rand = "0.8.5"
serde_json = "1.0"
serde_derive = "1.0.190"
serde = "1.0.136"
anchor-lang = "0.29.0"
plerkle_serialization = { git = "https://github.com/n00m4d/digital-asset-validator-plugin.git" }
async-recursion = "1.1.1"
thiserror = "1.0.31"

[dev-dependencies]
futures = "0.3.30"
