[package]
name = "usecase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.75"
entities = { path = "../entities" }
interface = { path = "../interface" }
tracing = "0.1.40"
solana-sdk = { version = "~1.17" }
metrics-utils = { path = "../metrics_utils" }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
solana-storage-bigtable = "~1.17"
solana-bigtable-connection = "1.10.31"
solana-transaction-status = "~1.17"
mpl-bubblegum = "1.0.1-beta.4"
mockall = "0.12.0"
spl-account-compression = "0.3.0"
solana-client = "~1.17"
solana-program = "~1.17"
spl-concurrent-merkle-tree = "0.2.0"
rand = "0.8.5"
serde_json = "1.0"
serde_derive = "1.0.190"
serde = "1.0.136"
anchor-lang = "0.29.0"
plerkle_serialization = { version = "1.8.0" }
async-recursion = "1.1.1"
thiserror = "1.0.31"

[dev-dependencies]
futures = "0.3.30"
