[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tonic = "0.10.2"
prost = "0.12.3"
futures = { workspace = true }
solana-sdk = { workspace = true }
interface = { path = "../interface" }
entities = { path = "../entities" }
async-trait = { workspace = true }
thiserror = { workspace = true }
solana-transaction-status = { workspace = true }
serde_cbor = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }

[build-dependencies]
tonic-build = "0.10.2"  # Corresponding build tool for tonic
