[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait="0.1.74"
futures="0.3.29"
mockall = "0.12.0"
thiserror = "1.0.51"
entities = { path = "../entities" }
solana-sdk = "~1.17"
solana-client = "~1.17"
plerkle_serialization = "1.8.0"
solana-transaction-status = "~1.17"
solana-storage-bigtable = "~1.17"
solana-program = "~1.17"
reqwest = { version = "0.11.23", features = ["json"] }
anchor-lang = "0.29.0"
serde_json = "1.0"
serde_derive = "1.0.190"
tokio = { version = "1.26.0", features = ["full", "tracing"] }
jsonrpc-core = {version = "19.0.0", git = "https://github.com/RequescoS/jsonrpc-response-middleware.git"}
