[package]
name = "integrity-verification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metrics-utils = { path = "../metrics_utils" }
usecase = { path = "../usecase" }
postgre-client = { path = "../postgre-client" }
entities = { path = "../entities" }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
thiserror = "1.0.56"
clap = { version = "4.4.14", features = ["derive"] }
tracing = {version = "0.1.40", features = ["log"]}
env_logger = "0.10.1"
reqwest = { version = "0.11.23", features = ["json"] }
figment = { version = "0.10.6", features = ["env"] }
serde_json = "1.0"
serde_derive = "1.0.190"
serde = "1.0.136"
dotenvy = "0.15.7"
rand = "0.8.5"
tokio-util = "0.7.10"
assert-json-diff = "2.0.2"
regex = "1.10.2"

[dev-dependencies]
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }