[package]
name = "postgre-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["full", "tracing"] }
sqlx = { version = "0.6.2", features = ["macros", "runtime-tokio-rustls", "postgres", "uuid", "offline", "json"] }
rocks-db = { path = "../rocks-db" }
mockall = "0.11.4"
async-trait = "0.1.74"
serde = "1.0.193"
base64 = "0.21.5"
entities = { path = "../entities" }
solana-sdk = "~1.16"
tracing  ="0.1.40"

[dev-dependencies]
setup = { path = "../tests/setup" }
testcontainers = "0.14.0"
uuid = { version = "1.6.1", features = ["v4"] }
rand = "0.8.5"
once_cell = "1.19.0"
lazy_static = "1.4.0"
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }

[features]
integration_tests = []