apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.secret" . }}
data:
  APP_DATABASE_URL: {{ .Values.api.db_url | b64enc | quote }}
  APP_READER_DATABASE_URL: {{ .Values.api.reader_db_url | b64enc | quote }}