name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (without v prefix, e.g. 0.5.0)'
        required: true
        type: string
      base_commit:
        description: 'Base commit SHA (leave empty to use latest develop)'
        required: false
        type: string
        default: ''

# Add permissions for GitHub operations
permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ inputs.version }} # Output the version for use in other jobs
      tag_name: v${{ inputs.version }}
      release_branch: release/v${{ inputs.version }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_commit || 'develop' }}
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: Setup environment
        run: ./scripts/release/setup_environment.sh

      - name: Create release branch
        run: ./scripts/release/create_release_branch.sh "${{ inputs.version }}"

      - name: Update version numbers
        run: ./scripts/release/update_versions.sh "${{ inputs.version }}"

      - name: Generate changelog
        id: changelog
        run: ./scripts/release/prepare_changelog.sh "${{ inputs.version }}"

      - name: Create pull request
        run: ./scripts/release/create_release_pr.sh "v${{ inputs.version }}" "main" "${{ env.RELEASE_BRANCH }}"

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md
