name: Rust CI

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings -W rust-2021-compatibility"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/
          ~/.cargo/git/
          target/
        key: ${{ runner.os }}-cargo-uchain

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Append to Cargo.toml
      run: |
        echo "[profile.dev]" >> Cargo.toml
        echo "debug = 0" >> Cargo.toml

    - name: Install Rust specific version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75
        profile: minimal
        components: clippy, rustfmt
        override: true

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Lint with Clippy
      run: cargo clippy --all -- -D warnings
      
    - name: Compile tests
      run: cargo test --no-run --locked --features integration_tests

    - name: Run tests
      run: cargo test -- --nocapture --quiet --features integration_tests