name: Rust CI

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings -W rust-2021-compatibility"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Install Rust specific version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75
        profile: minimal
        components: clippy, rustfmt
        override: true

    - name: Restore cargo cache
      id: cache-cargo
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Append to Cargo.toml
      run: |
        echo "[profile.dev]" >> Cargo.toml
        echo "debug = 0" >> Cargo.toml

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Lint with Clippy
      run: cargo clippy --all -- -D warnings --allow=deprecated

    - name: Save cargo cache
      id: cache-cargo-save
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ steps.cache-cargo.outputs.cache-primary-key }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Rust specific version
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75
          profile: minimal
          components: clippy, rustfmt
          override: true

      - name: Restore cargo cache
        id: cache-cargo
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Append to Cargo.toml
        run: |
          echo "[profile.dev]" >> Cargo.toml
          echo "debug = 0" >> Cargo.toml

      - name: Compile tests
        run: cargo test --no-run --locked --features integration_tests

      - name: Save cargo cache
        id: cache-cargo-save
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-cargo.outputs.cache-primary-key }}

      - name: Run tests
        run: cargo test --features integration_tests -- --nocapture --quiet